---
# Source: mayastor/templates/pool.yaml
apiVersion: "openebs.io/v1alpha1"
kind: MayastorPool
metadata:
  # Name can be anything as long as it is unique
  name: pool-on-NODE_NAME
  # or let k8s to generate a unique pool name
  #generateName: pool-
  namespace: mayastor
spec:
  node: NODE_NAME
  # ATM only one disk device is supported (i.e. /dev/nvme1n1)
  disks: ["DEVICE"]
